version: 0.1

phases: 
  install: 
   runtime-versions:
      nodejs: 16
  pre_build:
    commands:
      - yarn install

  build:
    commands:
      - yarn build


artifacts:
  files:
    - "**/*"
  discard-paths: no
  base-directory: build