version: 0.2

phases: 
  install: 
    commands:
      - n 16.14.1
      - apt-get update
      - apt-get install -y nodejs
      - node --version
      - apt install yarn

  pre_build:
    commands:
      - yarn install

  build:
    commands:
      - yarn build


artifacts:
  files:
    - "**/*"
  discard-paths: no
  base-directory: build