version: 0.2

phases: 
  install: 
    commands:
      - curl -fsSL https://deb.nodesource.com/setup_16.x | sudo -E bash -
      - sudo apt-get install -y nodejs
      - apt install yarn

  pre_build:
    commands:
      - yarn install

  build:
    commands:
      - yarn build


artifacts:
  files:
    - "**/*"
  discard-paths: no
  base-directory: build