version: 0.1

phases: 
  install: 
    commands: 
      - curl -fsSL https://deb.nodesource.com/setup_16.x | sudo -E bash -
      - apt-get install -y nodejs
  pre-build:
    commands:
      - yarn install

  build:
    commands:
      - yarn build


artifacts:
  files:
    -"**/*"
  discard-paths: no
  base-directory: build